android {
    flavorDimensions += "flavor-type"

    productFlavors {
        dev {
            dimension "flavor-type"
            applicationId "com.codewithandrea.flutter_ship_app.dev"
            resValue "string", "app_name", "Flutter Ship Dev"
        }
        stg {
            dimension "flavor-type"
            applicationId "com.codewithandrea.flutter_ship_app.stg"
            resValue "string", "app_name", "Flutter Ship Stg"
        }
        prod {
            dimension "flavor-type"
            applicationId "com.codewithandrea.flutter_ship_app"
            resValue "string", "app_name", "Flutter Ship"
        }
    }
}